import { useState, type FormEvent, type ReactNode } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "../lib/api";
import type { OAuthPolicy, OAuthAccess, OAuthSettings } from "../lib/oauth";
import { useToast } from "../context/ToastContext";

function Check({ label, checked, onChange, disabled = false }: { label: string; checked: boolean; onChange: (value: boolean) => void; disabled?: boolean }) {
 return <label className="flex items-start gap-2 break-all text-sm"><input className="mt-1" type="checkbox" checked={checked} disabled={disabled} onChange={e => onChange(e.target.checked)} /><span>{label}</span></label>;
}
const toggle = (values: string[], item: string, add: boolean) => add ? [...new Set([...values, item])] : values.filter(v => v !== item);
function SaveForm({ children, save, label }: { children: ReactNode; save: () => Promise<unknown>; label: string }) {
 const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const { push } = useToast();
 const submit = async (e: FormEvent) => { e.preventDefault(); if (busy) return; setBusy(true); setError(""); try { await save(); push("success", "OAuth permissions saved. Existing grants were revoked."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save permissions."); } finally { setBusy(false); } };
 return <form className="flex flex-col gap-5" onSubmit={e => void submit(e)}><fieldset disabled={busy} className="flex min-w-0 flex-col gap-5">{children}</fieldset>{error && <p role="alert" className="text-sm text-err">{error}</p>}<div className="form-actions"><button className="btn btn-primary" disabled={busy}>{busy ? "Saving…" : label}</button></div></form>;
}
export function ClientOAuthPermissions({ id, grants, confidential }: { id: string; grants: string[]; confidential: boolean }) {
 const [open, setOpen] = useState(false);
 const settings = useQuery({ queryKey: ["oauth-settings"], queryFn: api.oauthSettings, enabled: open });
 const policy = useQuery({ queryKey: ["oauth-policy", id], queryFn: () => api.oauthPolicy(id), enabled: open });
 return <section className="card min-w-0"><h2 className="font-semibold">OAuth permissions</h2><p className="my-3 text-sm text-ink-muted">Control API grants, resource scopes, offline access, and token inspection. Saving changes revokes this client's existing grants.</p><button type="button" className="btn btn-secondary" aria-expanded={open} onClick={() => setOpen(!open)}>{open ? "Hide OAuth permissions" : "Configure OAuth permissions"}</button>{open && <div className="mt-5">{settings.error || policy.error ? <p role="alert" className="text-err">Unable to load OAuth permissions. <button className="underline" onClick={() => { void settings.refetch(); void policy.refetch(); }}>Retry</button></p> : settings.data && policy.data ? <ClientPolicyForm key={id} id={id} initial={policy.data} settings={settings.data} grants={grants} confidential={confidential} /> : <p role="status">Loading permissions…</p>}</div>}</section>;
}
function ClientPolicyForm({ id, initial, settings, grants, confidential }: { id: string; initial: OAuthPolicy; settings: OAuthSettings; grants: string[]; confidential: boolean }) {
 const [policy, setPolicy] = useState<OAuthPolicy>(() => ({ ...initial, grants: initial.grants ?? [], resources: initial.resources ?? {}, introspectionAudiences: initial.introspectionAudiences ?? [] })); const cache = useQueryClient();
 const update = (patch: Partial<OAuthPolicy>) => setPolicy(p => ({ ...p, ...patch }));
 return <SaveForm label="Save OAuth permissions" save={async () => { const saved = await api.saveOAuthPolicy(id, policy); cache.setQueryData(["oauth-policy", id], saved); void cache.invalidateQueries({ queryKey: ["activity"] }); void cache.invalidateQueries({ queryKey: ["activity-overview"] }); }}>
  <fieldset className="form-section"><legend className="form-section-title">Grant permissions</legend><p className="form-section-description">Register a grant in the client settings before enabling it here.</p>
   <Check label="Client credentials — machine access" disabled={!confidential || !grants.includes("client_credentials")} checked={policy.grants.includes("client_credentials")} onChange={v => update({ grants: toggle(policy.grants, "client_credentials", v) })} />
   <Check label="Refresh tokens — offline access after explicit consent" disabled={!settings.refreshTokensEnabled || !grants.includes("refresh_token") || !grants.includes("authorization_code")} checked={policy.refreshEnabled} onChange={v => update({ refreshEnabled: v, grants: toggle(policy.grants, "refresh_token", v) })} />
   {!settings.refreshTokensEnabled && <p className="text-xs text-ink-faint">Refresh tokens are disabled in server configuration.</p>}
   <Check label="Legacy password grant" disabled={!settings.passwordGrantEnabled || !confidential || !grants.includes("password")} checked={policy.passwordEnabled} onChange={v => update({ passwordEnabled: v, grants: toggle(policy.grants, "password", v) })} />
   <p className="text-xs text-ink-muted">Password grant is disabled by default and prohibited by current OAuth security best practice. Prefer authorization code with PKCE. Enabling this legacy option also requires explicit resource entitlements on the user.</p>
  </fieldset>
  <fieldset className="form-section"><legend className="form-section-title">API resources and scopes</legend><p className="form-section-description">Allowed scopes cap token requests. Default scopes apply when the request omits scope.</p>
   {settings.resources.length === 0 && <p className="text-sm text-ink-muted">No API resources configured. Add trusted audiences and scopes to the server's OAuth configuration.</p>}
   {settings.resources.map(r => { const current = policy.resources[r.audience]; return <fieldset key={r.audience} className="min-w-0 rounded-lg border border-line p-4"><legend className="max-w-full break-all px-1 text-sm font-medium">{r.audience}{!r.enabled && " (disabled)"}</legend><Check label="Permit this resource" checked={!!current} onChange={v => { const resources = { ...policy.resources }; if (v) resources[r.audience] = { allowed: [], default: [] }; else delete resources[r.audience]; update({ resources, defaultResource: !v && policy.defaultResource === r.audience ? "" : policy.defaultResource }); }} />{current && <div className="mt-4 grid gap-4 sm:grid-cols-2"><div><h4 className="mb-2 text-xs font-medium text-ink-muted">Allowed scopes</h4>{r.scopes.map(sc => <Check key={sc} label={sc} checked={current.allowed.includes(sc)} onChange={v => update({ resources: { ...policy.resources, [r.audience]: { allowed: toggle(current.allowed, sc, v), default: v ? current.default : current.default.filter(s => s !== sc) } } })} />)}</div><div><h4 className="mb-2 text-xs font-medium text-ink-muted">Default scopes</h4>{current.allowed.map(sc => <Check key={sc} label={sc} checked={current.default.includes(sc)} onChange={v => update({ resources: { ...policy.resources, [r.audience]: { ...current, default: toggle(current.default, sc, v) } } })} />)}</div></div>}</fieldset>; })}
   <label className="flex flex-col gap-1.5 text-sm font-medium">Default resource<select className="input" value={policy.defaultResource} onChange={e => update({ defaultResource: e.target.value })}><option value="">Require resource in each request</option>{Object.keys(policy.resources).map(a => <option key={a}>{a}</option>)}</select></label>
  </fieldset>
  <fieldset className="form-section"><legend className="form-section-title">Token introspection</legend><p className="form-section-description">Confidential clients can inspect only the audiences selected here.</p><Check label="Allow token introspection" disabled={!confidential} checked={policy.introspectionEnabled} onChange={v => update({ introspectionEnabled: v, refreshInspection: v && policy.refreshInspection })} />{policy.introspectionEnabled && <>{["userinfo", ...settings.resources.map(r => r.audience)].map(a => <Check key={a} label={a} checked={policy.introspectionAudiences.includes(a)} onChange={v => update({ introspectionAudiences: toggle(policy.introspectionAudiences, a, v) })} />)}<Check label="Also inspect this client's own refresh tokens" checked={policy.refreshInspection} onChange={v => update({ refreshInspection: v })} /></>}</fieldset>
 </SaveForm>;
}
export function UserOAuthPermissions({ id }: { id: string }) {
 const [open, setOpen] = useState(false); const settings = useQuery({ queryKey: ["oauth-settings"], queryFn: api.oauthSettings, enabled: open }); const access = useQuery({ queryKey: ["oauth-access", id], queryFn: () => api.oauthAccess(id), enabled: open });
 return <section className="card min-w-0"><h2 className="font-semibold">OAuth resource access</h2><p className="my-3 text-sm text-ink-muted">Explicit user scopes for the legacy password grant. Application roles do not grant API scopes. Saving revokes existing user grants.</p><button type="button" className="btn btn-secondary" aria-expanded={open} onClick={() => setOpen(!open)}>{open ? "Hide resource access" : "Configure resource access"}</button>{open && <div className="mt-5">{settings.error || access.error ? <p role="alert" className="text-err">Unable to load resource access. <button className="underline" onClick={() => { void settings.refetch(); void access.refetch(); }}>Retry</button></p> : settings.data && access.data ? <UserAccessForm key={id} id={id} initial={access.data} settings={settings.data} /> : <p role="status">Loading resource access…</p>}</div>}</section>;
}
function UserAccessForm({ id, initial, settings }: { id: string; initial: OAuthAccess; settings: OAuthSettings }) {
 const [access, setAccess] = useState(initial); const cache = useQueryClient();
 return <SaveForm label="Save resource access" save={async () => { const saved = await api.saveOAuthAccess(id, access); cache.setQueryData(["oauth-access", id], saved); void cache.invalidateQueries({ queryKey: ["activity"] }); void cache.invalidateQueries({ queryKey: ["activity-overview"] }); }}>
  {!settings.resources.length && <p className="text-sm text-ink-muted">No API resources configured.</p>}
  {settings.resources.map(r => <fieldset key={r.audience} className="form-section"><legend className="form-section-title break-all">{r.audience}{!r.enabled && " (disabled)"}</legend><div className="grid gap-3 sm:grid-cols-2">{r.scopes.map(sc => <Check key={sc} label={sc} checked={(access[r.audience] ?? []).includes(sc)} onChange={v => setAccess(a => ({ ...a, [r.audience]: toggle(a[r.audience] ?? [], sc, v) }))} />)}</div></fieldset>)}
 </SaveForm>;
}
